# Generated by Django 5.0.4 on 2024-05-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturers',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='lecturerName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='preferredTimeslot',
            field=models.CharField(max_length=50),
        ),
    ]
