# Generated by Django 5.0.4 on 2024-05-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_lecturers_options_alter_lecturers_lecturername_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='courses',
            name='allottedBatch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
