# Generated by Django 5.0.4 on 2024-05-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_courses_options_alter_courses_allottedbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseCode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
