# Generated by Django 5.0.4 on 2024-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_courses_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='day',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='endTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='startTime',
            field=models.CharField(max_length=50),
        ),
    ]
