# Generated by Django 5.0.4 on 2024-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_timeslots_day_alter_timeslots_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='TimeslotsPerDay',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='daysPerWeek',
            field=models.IntegerField(null=True),
        ),
    ]
